codecov:
    require_ci_to_pass: false
coverage:
    status:
        project:
            default:
                target: 100%
                threshold: 1%
        patch:
            target: 100%
            threshold: 1%
comment: false
