name: Deploy

on:
    workflow_run:
        workflows: [CI]
        types: [completed]
        branches: [main]

jobs:
    production-deploy:
        name: Deploy to Production
        if: ${{ github.repository == 'UoA-Discords/server-registry-api' && github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        concurrency: production_environment
        steps:
            - name: Execute remote build process
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd services_v2/uoa-discords/server-registry-api
                      chmod +x scripts/deploy.sh
                      ./scripts/deploy.sh
